variable "database_name" {}
variable "database_password" {}
variable "database_user" {}
variable "region" {}
variable "AZ1" {}
variable "AZ2" {}
variable "AZ3" {}
variable "AZ4" {}
variable "VPC_cidr" {}
variable "subnet1_cidr" {}
variable "subnet2_cidr" {}
variable "subnet3_cidr" {}
variable "subnet4_cidr" {}
variable "instance_type" {}
variable "instance_class" {}
variable "PUBLIC_KEY_PATH" {}
variable "PRIV_KEY_PATH" {}
variable "root_volume_size" {}
variable "access_key_aws" {}
variable "secret_key_aws" {}
